CREATE TABLE IF NOT EXISTS DZKC_TRQK (
	ID TEXT NOT NULL,
	SF TEXT,
	KZ TEXT,
	XMS INTEGER,
	DZKC_HJ INTEGER,
	ZY_DCPJZX INTEGER,
	ZY_DZKCJJ INTEGER,
	DF_DZKCJJ INTEGER,
	QSY_GN INTEGER,
	QSY_GATS INTEGER,
	QSY_WS INTEGER,
	DZKC_QT INTEGER,
	NMCYRU_JS INTEGER,
	NMCYRU_QT INTEGER,
	PRIMARY KEY (ID)
);

